name: terradiff
version: 0.1.0.0
homepage: https://github.com/jml/terradiff#readme
license: AGPL
author: Jonathan Lange
maintainer: jml@mumak.net
copyright: (c) 2018 Jonathan M. Lange

extra-source-files:
  - README.rst
  - CHANGELOG.rst

synopsis: Terraforming with style
category: Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README file.
description: Please see the README on GitHub at <https://github.com/jml/terradiff#readme>

ghc-options: -Wall -Werror
default-extensions:
  - NamedFieldPuns  # Allow `FooRecord{foo, bar, baz} = fooRecord`
  - NoImplicitPrelude  # We use Protolude as the standard Prelude
  - OverloadedStrings  # Allow Haskell to interpret string literals as Text, ByteString, etc.

dependencies:
  - base >= 4.7 && < 5
  - protolude

library:
  source-dirs: src
  dependencies:
    - aeson
    - attoparsec
    - bytestring
    - clock
    - jml-web-service
    - lucid
    - network-uri
    - optparse-applicative
    - process
    - servant >= 0.14  # Get the better linking utilities
    - servant-lucid
    - servant-server >= 0.14
    - stm
    - time
    - unix

benchmarks:
  terradiff-benchmarks:
    source-dirs: benchmarks
    main: Main.hs
    dependencies:
      - terradiff
      - criterion
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

tests:
  terradiff-tests:
    source-dirs: tests
    main: Main.hs
    dependencies:
      - terradiff
      - hedgehog
      - tasty
      - tasty-discover
      - tasty-hedgehog
      - tasty-hspec
    ghc-options:
      - -rtsopts
      - -threaded
      - -with-rtsopts=-N

executables:
  terradiff:
    main: Main.hs
    source-dirs: cmd
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - terradiff
      - optparse-applicative

